server:  
  port: 9501
spring:
  datasource:
    name: order-db
    url: jdbc:mysql://172.18.5.110:3306/order_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20


  
