server:
  port: 8075
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:
  datasource:
    name: order_db
    url: jdbc:mysql://172.18.5.110:3306/coojisu-userInfo-service?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
coojisu:
    userInfo:
      nickname-generate:
        prefix：用户
