spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://172.18.5.110:3306/lotterydb_wjm_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
