spring:
  datasource:
    name: order_db
#    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    url: jdbc:mysql://172.18.5.110:3306/game?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20


server:
  port: 9006
  servlet:
    context-path: /game
