server:
  port: 9002
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:
  datasource:
    name: order_db
#    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    url: jdbc:mysql://172.18.5.110:3306/game?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
