spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://172.18.10.73:3306/lotterydb_access
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
