spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://172.18.5.110:3306/lotterydb_access?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20

  rabbitmq:
    host: 172.18.10.12
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: myvhost
