server:  
  port: 9087
eureka:  
  instance:  
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
 
spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://127.0.0.1:3306/security_common
    username: cmanager
    password: cmanager
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
