spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://172.18.5.110:3306/academysecuritydb
    username: cmanager
    password: cmanager
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
