spring:
  datasource:
    url: jdbc:mysql://172.16.1.118:3306/academysecuritydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xinwei2017#
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20
