spring:
  datasource:
    name: lottery_db_name
    url: jdbc:mysql://172.18.5.110:3306/academysecuritydb
    username: cmanager
    password: cmanager
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 5
      max-active: 20

  redis:
    cluster:
      nodes:
      - 101.200.166.163:9000
      - 101.200.166.163:9001
      - 101.200.166.163:9002
      - 101.200.166.163:9003
      - 101.200.166.163:9004
      - 101.200.166.163:9005   
